sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R k ASH BONE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R k BONE BREAST mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R k BONE I mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R k BONE KNEE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R k BONE NOSE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R k BONE ROUND mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R k BONE SMALL mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R k BONE TONGUE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R k BONE WE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R l ASH TONGUE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R l BONE TONGUE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R l BREAST TONGUE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R l I TONGUE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R l KNEE TONGUE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R l NOSE TONGUE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R l ROUND TONGUE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R l SMALL TONGUE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R l TONGUE WE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R m ASH BREAST mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R m BONE BREAST mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R m BREAST I mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R m BREAST KNEE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R m BREAST NOSE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R m BREAST ROUND mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R m BREAST SMALL mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R m BREAST TONGUE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R m BREAST WE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R n ASH NOSE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R n ASH WE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R n BONE NOSE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R n BONE WE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R n BREAST NOSE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R n BREAST WE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R n I NOSE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R n I WE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R n KNEE NOSE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R n KNEE WE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R n NOSE ROUND mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R n NOSE SMALL mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R n NOSE TONGUE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R n NOSE WE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R n ROUND WE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R n SMALL WE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R n TONGUE WE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R u ASH BONE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R u ASH BREAST mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R u ASH I mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R u ASH KNEE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R u ASH NOSE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R u ASH ROUND mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R u ASH SMALL mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R u ASH TONGUE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R u ASH WE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R u BONE KNEE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R u BREAST KNEE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R u I KNEE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R u KNEE NOSE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R u KNEE ROUND mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R u KNEE SMALL mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R u KNEE TONGUE mcc
sbatch run_job.sh Rscript run_model_pairwise_concepts_by_seg.R u KNEE WE mcc
